[package]
name = "movexo3"
version = "0.1.0"
authors = ["Julian True <julian.allan.true@gmail.com>"]
edition = "2018"
publish = false

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[lib]
name = "movexo3"
crate-type = ["cdylib"]
